let solution = "";
let input = "";

let guessCount = 1;
let guessLimit = 5;
let wordLength = 5;

let wordBank = [];

//get solution word
solution = getSolutionWord();
solution = solution.toString().toUpperCase().trim();

function onSubmit() {
  //clear any previous errors
  error(null);

  if (guessCount <= guessLimit) {
    //get user text from textbox
    input = document.getElementById("userInput").value;
    input = input.toString().toUpperCase().trim();

    //validate user text
    if (input.length != wordLength) {
      error("Your guess must be 5 characters");
      return;
    }

    //get the current guess row
    letters = document
      .getElementById("guessContainer_" + guessCount)
      .getElementsByClassName("guessLetter");

    for (x = 0; x <= input.length - 1; x++) {
      //put each input letter into its slot and color gray by default
      letters[x].textContent = input.charAt(x);
      letters[x].style.backgroundColor = "#31302f";

      if (solution.includes(input.charAt(x))) {
        //input char exists in solution word: color character yellow
        letters[x].style.backgroundColor = "#C9A647";
        if (input.charAt(x) === solution.charAt(x)) {
          //input char matches solution char at x, color character green
          letters[x].style.backgroundColor = "#79a54d";
        }
      }
    } //end forloop

    //on last guess, didn't win
    if (guessCount == guessLimit && input.localeCompare(solution) != 0) {
      gameOver(false, "No more guesses :( Try again!");
      return;
    }

    //winning scenario
    if (input.localeCompare(solution) == 0) {
      gameOver(true, "You won! Want to play again?");
      return;
    }

    //increment count and clear the textbox to continue guessing
    guessCount++;
    document.getElementById("userInput").value = null;
  } 
} //end onSubmit

function gameOver(wonTF, message) {
  document.getElementById("infoContainer").innerText = message;
  if(!wonTF)
    document.getElementById("infoContainer").style.color = "#f3ebd5"

  document.getElementById("resetButton").style = "visibility:visible";
  document.getElementById("userInput").disabled = true;
  document.getElementById("guessButton").disabled = true;
}

function error(message) {
  document.getElementById("errorContainer").innerText = message;
}

function onReset() {
  location.reload();
}

function getSolutionWord() {
  wordBank = [
    "white",
    "smile",
    "night",
    "words",
    "snide",
    "round",
    "dizzy",
    "mouth",
    "dying",
    "these",
    "trees",
    "their",
    "smoke",
    "holes",
    "cocoa",
    "beard",
    "turns",
    "those",
    "times",
    "quiet",
    "packs",
    "baked",
    "froth",
    "fight",
    "dance",
    "wings",
    "slick",
    "slice",
    "sleep",
    "slate",
    "waxen",
    "stare",
    "young",
    "eager",
    "milky",
    "heavy",
    "knees",
    "cheek",
    "fruit",
    "fresh",
    "hands",
    "icing",
    "makes",
    "glass",
    "palms",
    "dirty",
    "nails",
    "slimy",
    "pulls",
    "blind",
    "wanna",
    "right",
    "windy",
    "mover",
    "truck",
    "sloth",
    "curls",
    "shake",
    "bones",
    "bring",
    "snake",
    "child",
    "plush",
    "capes",
    "black",
    "mambo",
    "cheat",
    "flush",
    "veins",
    "exxus",
    "blink",
    "stuff",
    "salty",
    "rusty",
    "place",
    "calls",
    "spend",
    "maybe",
    "walls",
    "watch",
    "navel",
    "yearn",
    "whole",
    "doubt",
    "lying",
    "stuck",
    "truth",
    "other",
    "under",
    "knife",
    "looms",
    "blood",
    "empty",
    "tombs",
    "tooth",
    "where",
    "brain",
    "break",
    "gotta",
    "funny",
    "rabid",
    "bloom",
    "until",
    "loose",
    "float",
    "comes",
    "wisps",
    "chest",
    "world",
    "noise",
    "tools",
    "guilt",
    "which",
    "poise",
    "shore",
    "hills",
    "beach",
    "ultra",
    "pools",
    "tired",
    "shook",
    "close",
    "slang",
    "naked",
    "while",
    "gooey",
    "woozy",
    "youth",
    "dopes",
    "silky",
    "gonna",
    "vibes",
    "tipsy",
    "topsy",
    "slurs",
    "space",
    "gloom",
    "timid",
    "honey",
    "bunny",
    "trick",
    "rhyme",
    "walla",
    "fangs",
    "hazey",
    "booze",
    "drain",
    "photo",
    "spark",
    "still",
    "funky",
    "swine",
    "purrs",
    "apart",
    "thing",
    "thick",
    "flume",
    "dunes",
    "hairs",
    "super",
    "lemon",
    "gross",
    "pipes",
    "mondo",
    "rolls",
    "fuzzy",
    "drone",
    "cries",
    "final",
    "taste",
    "leave",
    "plant",
    "wrong",
    "never",
    "climb",
    "scene",
    "dream",
    "tight",
    "think",
    "flame",
    "bitch",
    "river",
    "shark",
    "money",
    "heart",
    "death",
    "steel",
    "charm",
    "floor",
    "store",
    "rasta",
    "devil",
    "false",
    "trust",
    "begin",
    "hella",
    "crazy",
    "daddy",
    "tough",
    "human",
    "loved",
    "quite",
    "boxes",
    "tesco",
    "flash",
    "sonic",
    "meant",
    "happy",
    "laugh",
    "dappy",
    "right",
    "ghost",
    "every",
    "tried",
    "lunch",
    "belly",
    "phone",
    "three",
    "could",
    "hurts",
    "drunk",
    "cliff",
    "again",
    "dress",
    "house",
    "drank",
    "sweet",
    "voice",
    "broke",
    "doing",
    "steam",
    "glare",
    "drugs",
    "green",
    "rails",
    "seeds",
    "agave",
    "might",
    "shove",
    "shirt",
    "looks",
    "pants",
    "worry",
    "spoke",
    "coats",
    "jumbo",
    "treat",
    "blame",
    "stone",
    "pappy",
    "vogue",
    "prize",
    "rings",
    "prime",
    "tasty",
    "price",
    "lived",
    "keats",
    "crisp",
    "woman",
    "lower",
    "teeth",
    "agnes",
    "clear",
    "guess",
    "first",
    "worst",
    "touch",
    "movie",
    "album",
    "cream",
    "ramen",
    "sugar",
    "light",
    "since",
    "tints",
    "strat",
    "flips",
    "juice",
    "coast",
    "yours",
    "quake",
    "metal",
    "porno",
    "tapes",
    "bored",
    "norms",
    "being",
    "alone",
    "stole",
    "metro",
    "small",
    "texas",
    "capri",
    "straw",
    "heard",
    "names",
    "frame",
    "disco",
    "tokyo",
    "gears",
    "scoot",
    "wavey",
    "davey",
    "spent",
    "trout",
    "wrist",
    "spout",
    "melon",
    "melly",
    "feels",
    "would",
    "doing",
    "force",
    "style",
    "beams",
    "shoes",
    "falls",
    "slide",
    "alive",
    "gimme",
    "dicks",
    "aries",
    "cheap",
    "booze",
    "pepsi",
    "gummy",
    "clown",
    "storm",
    "water",
    "drops",
    "sound",
    "bliss",
    "tears",
    "waves",
    "about",
    "today",
    "puppy",
    "skies",
    "broad",
    "vapor",
    "trail",
    "weeks",
    "drawn",
    "angel",
    "hymen",
    "throw",
    "stage",
    "grace",
    "party",
    "shine",
    "solar",
    "stand",
    "plans",
    "color",
    "jesus",
    "cried",
    "power",
    "reach",
    "learn",
    "spilt",
    "scars",
    "paper",
    "trunk",
    "speed",
    "again",
    "going",
    "safer",
    "haunt",
    "point",
    "crack",
    "state",
    "punch",
    "rules",
    "thank",
    "drive",
    "hoped",
    "great",
    "ideas",
    "lungs",
    "shape",
    "chasm",
    "faded",
    "jelly",
    "apple",
    "older",
    "early",
    "roses",
    "burst",
    "hated",
    "piece",
    "stray",
    "sunny",
    "shows",
    "liked",
    "track",
    "socks",
    "paint",
    "swear",
    "clean",
    "years",
    "abort",
    "ocean",
    "flood",
    "press",
    "third",
  ];

  return wordBank[getRandomInt(0, wordBank.length - 1)]
}

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
